name: Pokeball Vue CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_IMAGE: iqmal1999/pokeball-vue3

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          TAG: ${{ github.sha }}
        run: |
          docker build -t iqmal1999/pokeball-vue3:latest .
          docker push iqmal1999/pokeball-vue3:latest
          echo "IMAGE=$DOCKER_IMAGE:$TAG" >> $GITHUB_ENV

